
import { Roboto } from 'next/font/google'
import Footer from "./components/Footer";
import "./globals.css";
import Navbar from './components/Navbar';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "App/Software Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
      <Footer />
      </body>
    </html>
  );
}
